
version: 2

models:
  - name: stg_reports_combined
    description: "union of 2019-2023 report tables in raw schema. includes renewable and non-renewable plants that were operating in the utility sector at the time of the report's release."
    columns:
      - name: report_plant_id
        description: "generated surrogate key identifying unique plant, unit, and eia reporting month"
        tests:
          - unique
          - not_null
  - name: stg_clean
    description: "2019-2023 reports of operating plants with relevant columns selected, filtered to renewable plants only, values renamed, and relevant columns selected."
    columns:
      - name: fuel_source
        tests:
         - accepted_values:
            values: ['SUN', 'WIND']

  - name: fct_unit_capacity
    description: "fact table with all power plant unit capacities for each eia report release."
    columns:
      - name: plant_unit_id
        tests:
          - relationships:
              to: ref('dim_plant_unit')
              field: plant_unit_id
          - not_null
      - name: report_date_id
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_id
          - not_null
  - name: dim_plant_unit
    description: "dimension table with all power plant unit descriptors."
    columns:
      - name: op_date_id
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_id

    