
version: 2

models:
  - name: stg_reports_combined
    description: "union of all report tables in raw schema"
    columns:
      - name: report_plant_id
        description: "primary key identifying unique plant, unit, and eia reporting month"
        tests:
          - unique
          - not_null
    