version: 2

sources:
  - name: raw
    database: eia860
    schema: raw
    tables:
      - name: reports_2023
      - name: reports_2022
      - name: reports_2021
      - name: reports_2020
      - name: reports_2019
      - name: usgs_solar_2023
      - name: usgs_wind_2023